# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'QRReaderPrototype' do

pod 'AFNetworking', '3.0.4'
pod 'SVProgressHUD', '1.1.3'

end

